<html>

<head>
<meta http-equiv="Content-Language" content="zh-cn">
<meta http-equiv="Content-Type" content="text/html; charset=gb2312">
<title>鸿运彩票</title>
</head>

<body>

<table border="0" width="100%" cellspacing="1">
	<tr>
		<td>　</td>
		<td align="center">　</td>
		<td>　</td>
	</tr>
	<tr>
		<td>　</td>
		<td align="center">　</td>
		<td>　</td>
	</tr>
	<tr>
		<td>　</td>
		<td align="center">　</td>
		<td>　</td>
	</tr>
	<tr>
		<td>　</td>
		<td align="center">
		<p align="center"><a target="_blank" href="https://089hy.com/register?id=61220555">
		<img border="0" src="https://tinyurl.com/yxfnpnzd" width="500" height="100"></a></td>
		<td>　</td>
	</tr>
	<tr>
		<td>　</td>
		<td align="center">　</td>
		<td>　</td>
	</tr>
	<tr>
		<td>　</td>
		<td align="center">
		<b style="color: rgb(0, 0, 0); font-family: Microsoft YaHei; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: -webkit-center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial">
		<font color="#E72538" size="10"><span style="text-decoration: none">
		<a target="_blank" href="https://089hy.com/register?id=61220555" style="text-decoration: none">
		<font color="#E72538">089hy.com</font></a></span></font></b></td>
		<td>　</td>
	</tr>
	<tr>
		<td>　</td>
		<td align="center">　</td>
		<td>　</td>
	</tr>
	<tr>
		<td>　</td>
		<td align="center">
		<span style="color: rgb(0, 0, 0); font-family: Microsoft YaHei; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: -webkit-center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial">
		<font color="#E72538" size="10" face="方正兰亭特黑_GBK">
		<span style="text-decoration: none; letter-spacing: 5px; font-weight: 700">
		<a target="_blank" href="https://089hy.com/register?id=61220555" style="text-decoration: none">
		<font color="#E72538">请点击访问</font></a></span></font></span></td>
		<td>　</td>
	</tr>
	<tr>
		<td>　</td>
		<td align="center">　</td>
		<td>　</td>
	</tr>
	<tr>
		<td>　</td>
		<td align="center">
		<a target="_blank" href="https://089hy.com/register?id=61220555" style="text-decoration: none">
		<span style="letter-spacing: 5px"><b>
		<font face="华康标题宋W9(P)" size="10" color="#E72538">点击添加</font><font face="华康标题宋W9(P)" size="10" color="#00FF00">→</font></b></span></a><a target="_blank" href="https://hycpgw.github.io/hongyun.github.io/" style="text-decoration: none"><b style="color: rgb(0, 0, 0); font-family: Microsoft YaHei; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: -webkit-center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial"><span style="letter-spacing: 5px"><font face="华康标题宋W9(P)" size="10" color="#E72538">导师【1】Q：</font></span></b><b><font size="10" color="#E72538">77060273</font></b></a><span style="color:red"><p>
		<a target="_blank" href="https://089hy.com/register?id=61220555" style="text-decoration: none">
		<span style="letter-spacing: 5px"><b>
		<font face="华康标题宋W9(P)" size="10" color="#E72538">点击添加</font><font face="华康标题宋W9(P)" size="10" color="#00FF00">→</font></b></span></a><a target="_blank" href="https://hycpgw.github.io/qq2.github.io/" style="text-decoration: none"><b style="color: rgb(0, 0, 0); font-family: Microsoft YaHei; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: -webkit-center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial"><span style="letter-spacing: 5px"><font face="华康标题宋W9(P)" size="10" color="#E72538">导师【2】Q：</font></span></b><b><font color="#E72538" size="10">57679228</font></b></a></p>
		<p>
		<a target="_blank" href="https://089hy.com/register?id=61220555" style="text-decoration: none">
		<span style="letter-spacing: 5px"><b>　</td>
		<td>　<p>　</td>
	</tr>
</table>
<！-不蒜子计数->
< script  async  src = “ // // busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js ” > </ 脚本 >
< span  id = “ busuanzi_container_site_pv ”  style = ' display：none ' > | 总访问量< span  id = “ busuanzi_value_site_pv ” > </ span >次</ span >
< span  id = “ busuanzi_container_site_uv ”  style = ' display：none ' > | 总访客数< span  id = “ busuanzi_value_site_uv ” > </ span >人</ span >
<！-不蒜子计数->  
 
 
<！-不蒜子计数初始值校正->
< 脚本 >
$（文档）。准备好了（function（）{
 
    var int =  setInterval（fixCount，50）;  // 50ms周期检测函数
    var countOffset =  20000 ;  //初始化首次数据
 
    函数 fixCount（）{            
       如果（文件。的getElementById（“ busuanzi_container_site_pv ”）的风格。显示器 ！=  “无”）
        {
            $（“ #busuanzi_value_site_pv ”）。HTML（parseInt函数（$（“ #busuanzi_value_site_pv ”）。HTML（））+ countOffset）;
            clearInterval（int）;
        }                  
        if（$（“ #busuanzi_container_site_pv ”）。css（“ display ”）！=  “” none “）
        {
            $（“ #busuanzi_value_site_uv ”）。HTML（parseInt函数（$（“ #busuanzi_value_site_uv ”）。HTML（））+ countOffset）; //加上初始数据
            clearInterval（int）; //停止检测
        }  
    }
        
}）;
</ 脚本 >
</body>



</html>
